# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 22:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='se_imprime_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaccionventa',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaccionventa',
            name='tipo_transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.TipoTransaccion'),
        ),
    ]
