# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_agregada_cantidad_combo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='producto_combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combo_productos', to='MainApp.Producto'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='producto_padre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padres', to='MainApp.Producto'),
        ),
    ]
