# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_corregida_relacion_combo_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='combo_productos',
            field=models.ManyToManyField(through='MainApp.Combo', to='MainApp.Producto'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='producto_combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='MainApp.Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='combo',
            unique_together=set([('producto_combo', 'producto_padre')]),
        ),
    ]
