# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_perfilusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccioncontable',
            name='libro',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_baja',
            field=models.IntegerField(choices=[(1, b'P\xc3\xa9rdida'), (2, b'Robo'), (3, b'Devoluci\xc3\xb3n'), (4, b'Caducidad'), (5, b'Da\xc3\xb1o')], default=1),
        ),
    ]
