# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_transaccioncontable_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccioncontable',
            name='usuario',
        ),
    ]
