# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_remove_transaccioncontable_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccioncontable',
            name='tipo_movimiento',
            field=models.CharField(max_length=35),
        ),
    ]
