# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_auto_20160304_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('motivo', models.TextField(null=True)),
                ('numero_boleta', models.IntegerField(blank=True, null=True)),
                ('anulado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Persona')),
                ('tipo_gasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.TipoGasto')),
            ],
        ),
        migrations.AlterField(
            model_name='transaccionventa',
            name='tipo_transaccion',
            field=models.IntegerField(choices=[(1, 'Pedido'), (2, 'Cancelado'), (3, 'Cobrado')], default=1),
        ),
        migrations.DeleteModel(
            name='TipoTransaccion',
        ),
    ]
