# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-01 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_auto_20160323_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='comision_producto',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='comision_servicio',
        ),
    ]
