# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-04 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_auto_20160401_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='tipo_producto_combo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='padres', to='MainApp.TipoProducto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_fichas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_productos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='combo_mixto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='comision_mesero',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_minimo_producto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_fichas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='combo',
            name='producto_combo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='padres', to='MainApp.Producto'),
        ),
    ]
