# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-08 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_auto_20160408_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='codigo_barra',
            field=models.BooleanField(default=False),
        ),
    ]
