# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-19 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_persona_codigo_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='cuenta_separada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='nombre_cuenta',
            field=models.TextField(default=b'', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='transaccionventa',
            name='tipo_transaccion',
            field=models.IntegerField(choices=[(1, 'Pedido'), (2, 'Cancelado'), (3, 'Cobrado'), (4, 'Pendiente de Pago')], default=1),
        ),
    ]
