# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0019_add_separado_nombrecuenta_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
