# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-23 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_direccion_persona_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaccionventa',
            name='tipo_transaccion',
            field=models.IntegerField(choices=[(1, 'Pedido'), (2, 'Anulado'), (3, 'Cobrado'), (4, 'Pendiente de Pago')], default=1),
        ),
    ]
