# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-28 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0021_add_finalizacion_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallemovimiento',
            name='de_combo_mixto',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
