# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0023_add_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='nit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
