# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0024_nit_direccion_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='hash_codigo_barra',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
