# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0025_add_hash_codigo_barra'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='observacion',
            field=models.TextField(default=b'', max_length=250, null=True),
        ),
    ]
