# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0026_add_observacion_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='observacion',
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='observacion',
            field=models.TextField(default=b'', max_length=100, null=True),
        ),
    ]
