# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0027_add_observacion_detallemovimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='se_carga_a_empleada',
            field=models.BooleanField(default=False),
        ),
    ]
