# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0028_default_false_secargaempleada'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apertura', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cierre', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vendido', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('vendido_costo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.Caja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_Cierre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('denominacion', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('id_cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierre_caja', to='MainApp.CierreCaja')),
            ],
        ),
    ]
