# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0029_add_detalle_cierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleCierre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('denominacion', models.IntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('id_cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierre_caja', to='MainApp.CierreCaja')),
            ],
        ),
        migrations.RemoveField(
            model_name='detalle_cierre',
            name='id_cierre',
        ),
        migrations.DeleteModel(
            name='Detalle_Cierre',
        ),
    ]
