# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0030_add_rel_cierracaja_detalle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecierre',
            old_name='id_cierre',
            new_name='cierre',
        ),
    ]
