# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0031_rename_fk_cierre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecierre',
            name='cierre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle', to='MainApp.CierreCaja'),
        ),
    ]
