# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0032_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecierre',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallecierre',
            name='denominacion',
            field=models.IntegerField(default=0),
        ),
    ]
