# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-10 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0034_denominacion_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='observacion',
            field=models.TextField(blank=True, default=b'', max_length=100, null=True),
        ),
    ]
