# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-11 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0035_observacion_blank_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecierre',
            name='denominacion',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
