# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-12 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0037_add_pagos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
