# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0039_nombre_usuarios_a_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_fichas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='comision_mesero',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_fichas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='presentacion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='se_carga_a_empleada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='se_imprime_ticket',
        ),
    ]
