# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-02 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0040_add_tabla_productopresentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoPresentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('se_imprime_ticket', models.BooleanField(default=False)),
                ('comision_mesero', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cantidad_fichas', models.IntegerField(default=0)),
                ('precio_fichas', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('se_carga_a_empleada', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='MainApp.Presentacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_presentacion', to='MainApp.Producto')),
            ],
        ),
    ]
