# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-02 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0042_servido_detalle_movimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, b'Contratado'), (2, b'Recontratado'), (3, b'Despedido'), (4, b'Renuncia')])),
                ('fecha', models.DateField()),
                ('observacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='clasificacion_empleado',
            field=models.IntegerField(blank=True, choices=[(1, b'Bajo'), (2, b'Medio'), (3, b'Alto')], null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(default='N/A', max_length=45),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='sueldo_cuenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='historialempleado',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_contratacion', to='MainApp.Persona'),
        ),
    ]
