# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-06 23:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0044_identificacion_no_requiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_baile', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bailes_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BailePersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('baile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baile_personas', to='MainApp.Baile')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bailes_persona', to='MainApp.Persona')),
            ],
        ),
    ]
