# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-08 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0045_baile_persona_baile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bailepersona',
            name='baile',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='baile_personas', to='MainApp.Baile'),
            preserve_default=False,
        ),
    ]
