# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-17 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0046_correccion_baile_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='comsetible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='se_descuenta',
            field=models.BooleanField(default=True),
        ),
    ]
