# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-05 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0046_correccion_baile_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Configuracion')),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='cantidad_ficha',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='comision_mesero',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='detallemovimiento',
            name='precio_ficha',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detallemovimiento',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.ProductoPresentacion'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='cuenta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Cuenta'),
        ),
    ]
