# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-05 23:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0048_auto_20160705_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallemovimiento',
            old_name='producto_presentacion',
            new_name='producto',
        ),
    ]
