# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-06 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0049_auto_20160705_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gasto',
            new_name='DepositoRetiro',
        ),
        migrations.RenameModel(
            old_name='TipoGasto',
            new_name='TipoDepositoRetiro',
        ),
        migrations.RenameField(
            model_name='depositoretiro',
            old_name='tipo_gasto',
            new_name='tipo_deposito_retiro',
        ),
    ]
