# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-06 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0050_auto_20160706_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodepositoretiro',
            name='tipo_ingreso_egreso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipodepositoretiro',
            name='tipo_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.TipoPersona'),
        ),
    ]
