# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-09 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0051_auto_20160706_1231'),
        ('MainApp', '0047_campo_comestible_producto'),
    ]

    operations = [
    ]
