# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-09 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0052_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipodepositoretiro',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Configuracion'),
        ),
    ]
