# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-12 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0053_tipodepositoretiro_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositoretiro',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='tipodepositoretiro',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='tipodepositoretiro',
            name='tipo_persona',
        ),
        migrations.AddField(
            model_name='depositoretiro',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.Caja'),
        ),
        migrations.AddField(
            model_name='depositoretiro',
            name='cuenta_entrada',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_entrada', to='MainApp.Cuenta'),
        ),
        migrations.AddField(
            model_name='depositoretiro',
            name='cuenta_salida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_salida', to='MainApp.Cuenta'),
        ),
    ]
