# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-12 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0054_auto_20160712_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositoretiro',
            name='persona',
        ),
        migrations.AlterField(
            model_name='depositoretiro',
            name='tipo_deposito_retiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.TipoDepositoRetiro'),
        ),
    ]
