# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-13 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0055_auto_20160712_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositoretiro',
            old_name='cantidad',
            new_name='monto',
        ),
        migrations.RemoveField(
            model_name='depositoretiro',
            name='tipo_deposito_retiro',
        ),
        migrations.AddField(
            model_name='depositoretiro',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='depositoretiro',
            name='forma_pago',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.FormaPago'),
        ),
        migrations.AlterField(
            model_name='depositoretiro',
            name='motivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.TipoDepositoRetiro'),
        ),
    ]
