# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-15 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0057_auto_20160714_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuenta',
            name='empresa',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='configuracion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='MainApp.Configuracion'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='persona',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuenta', to='MainApp.Persona'),
        ),
    ]
