# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-15 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0058_auto_20160715_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuenta',
            old_name='configuracion',
            new_name='empresa',
        ),
    ]
