# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-15 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0060_auto_20160715_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositoretiro',
            name='tipo_persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.TipoPersona'),
        ),
    ]
