# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-19 15:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0061_depositoretiro_tipo_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositoretiro',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
