# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0063_auto_20160719_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='area',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
