# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-20 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0064_persona_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='area',
            field=models.IntegerField(blank=True, choices=[(1, b'Barra'), (2, b'Mesas'), (3, b'Pista'), (4, b'Servicio'), (5, b'VIP')], null=True),
        ),
    ]
