# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0067_auto_20160722_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='prod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productopresentacion', to='MainApp.ProductoPresentacion'),
        ),
        migrations.AlterField(
            model_name='detallemovimiento',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='MainApp.Producto'),
        ),
    ]
