# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-25 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0069_auto_20160722_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopresentacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
