# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-08 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0070_productopresentacion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositoretiro',
            name='movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='MainApp.Movimiento'),
        ),
    ]
