# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-09 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0071_depositoretiro_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoretiro',
            name='movimiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento_caja', to='MainApp.Movimiento'),
        ),
    ]
