# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0074_auto_20160810_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_pago',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
