# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-25 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0075_persona_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoretiro',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caja', to='MainApp.Caja'),
        ),
    ]
