# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-30 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0076_auto_20160825_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='bailepersona',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bailepersona',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
