# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-02 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0077_auto_20160830_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='no_repetir',
            field=models.BooleanField(default=True),
        ),
    ]
