# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-02 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0079_auto_20160902_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo',
            old_name='no_repetir',
            new_name='repetir',
        ),
    ]
