# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-12 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0080_auto_20160902_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='porcentaje_chica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
