# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0081_persona_porcentaje_chica'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositoretiro',
            name='semanal',
            field=models.BooleanField(default=False),
        ),
    ]
