# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-20 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0082_depositoretiro_semanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapago',
            name='motivo',
            field=models.TextField(default=b'', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='tipo',
            field=models.IntegerField(choices=[(1, b'Efectivo'), (2, b'Tarjeta de cr\xc3\xa9dito'), (3, b'Cheque'), (4, b'Cortesia')]),
        ),
    ]
