# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-24 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0083_auto_20160920_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopresentacion',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
