# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-24 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0084_productopresentacion_mostrar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='se_descuenta',
            field=models.BooleanField(default=False),
        ),
    ]
