# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-10-18 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0085_auto_20160924_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
