# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-16 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0088_persona_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='grupo',
            field=models.IntegerField(blank=True, choices=[(1, b'Bodeguero'), (2, b'Mesero'), (3, b'Cajero'), (4, b'Administrador'), (5, b'Cocina')], null=True),
        ),
    ]
