# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-16 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0089_auto_20161116_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='hash_codigo_barra',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
