# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-17 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0091_pagopersonal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagopersonal',
            name='vales',
        ),
    ]
