# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-18 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0092_remove_pagopersonal_vales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
