# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-21 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0093_auto_20161118_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
