# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-30 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0094_auto_20161121_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='productopresentacion',
            name='porcentaje_completo',
            field=models.BooleanField(default=False),
        ),
    ]
