# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-13 23:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0095_productopresentacion_porcentaje_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDetalleMovimiento',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('servido', models.BooleanField(default=False)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cortesia', models.BooleanField(default=False)),
                ('de_combo_mixto', models.IntegerField(default=None, null=True)),
                ('observacion', models.TextField(blank=True, default=b'', max_length=100, null=True)),
                ('creado', models.DateTimeField(blank=True, editable=False)),
                ('modificado', models.DateTimeField(blank=True, editable=False)),
                ('comision_mesero', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cantidad_ficha', models.IntegerField(default=None, null=True)),
                ('precio_ficha', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('movimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MainApp.Movimiento')),
                ('persona', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MainApp.Persona')),
                ('producto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MainApp.Producto')),
                ('producto_presentacion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MainApp.ProductoPresentacion')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical detalle movimiento',
            },
        ),
        migrations.CreateModel(
            name='HistoricalMovimiento',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, b'Ingreso'), (2, b'Venta'), (3, b'Baja')])),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_costo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('tipo_compra', models.IntegerField(choices=[(1, b'Contado'), (2, b'Cr\xc3\xa9dito')], default=1)),
                ('tipo_baja', models.IntegerField(choices=[(1, b'P\xc3\xa9rdida'), (2, b'Robo'), (3, b'Devoluci\xc3\xb3n'), (4, b'Caducidad'), (5, b'Da\xc3\xb1o')], default=1)),
                ('nombre_cuenta', models.TextField(default=b'', max_length=25, null=True)),
                ('cuenta_separada', models.BooleanField(default=False)),
                ('finalizado', models.BooleanField(default=False)),
                ('documento', models.PositiveSmallIntegerField(choices=[(1, b'Factura'), (2, b'Recibo'), (3, b'Vale')], default=1)),
                ('motivo', models.TextField(default=b'', max_length=500, null=True)),
                ('no_documento', models.CharField(max_length=30, null=True)),
                ('descuento', models.BooleanField(default=False)),
                ('porcentaje_descuento', models.IntegerField(blank=True, null=True)),
                ('monto_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('anulado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(blank=True, editable=False, null=True)),
                ('modificado', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mesa', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MainApp.Mesa')),
                ('persona', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MainApp.Persona')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical movimiento',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProducto',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio_costo', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('existencia', models.IntegerField(default=0)),
                ('existencia_minima', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('es_combo', models.BooleanField(default=False)),
                ('se_descuenta', models.BooleanField(default=False)),
                ('combo_mixto', models.BooleanField(default=False)),
                ('costo_minimo_producto', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cantidad_productos', models.IntegerField(default=0)),
                ('comsetible', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(blank=True, editable=False)),
                ('modificado', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_producto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='MainApp.TipoProducto')),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical producto',
            },
        ),
    ]
