# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-17 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0097_historicalproductopresentacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagopersonal',
            name='fecha_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pagopersonal',
            name='fecha_inicio',
            field=models.DateTimeField(null=True),
        ),
    ]
