# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-29 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0100_auto_20170130_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='impresora',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
