# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-06-04 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0101_persona_impresora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemovimiento',
            name='observacion',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='motivo',
            field=models.TextField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='formapago',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Efectivo'), (2, 'Tarjeta de crédito'), (3, 'Cheque'), (4, 'Cortesia')]),
        ),
        migrations.AlterField(
            model_name='historialempleado',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Contratado'), (2, 'Recontratado'), (3, 'Despedido'), (4, 'Renuncia')]),
        ),
        migrations.AlterField(
            model_name='historicaldetallemovimiento',
            name='observacion',
            field=models.TextField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmovimiento',
            name='documento',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Factura'), (2, 'Recibo'), (3, 'Vale')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalmovimiento',
            name='motivo',
            field=models.TextField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmovimiento',
            name='nombre_cuenta',
            field=models.TextField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmovimiento',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Venta'), (3, 'Baja')]),
        ),
        migrations.AlterField(
            model_name='historicalmovimiento',
            name='tipo_baja',
            field=models.IntegerField(choices=[(1, 'Pérdida'), (2, 'Robo'), (3, 'Devolución'), (4, 'Caducidad'), (5, 'Daño')], default=1),
        ),
        migrations.AlterField(
            model_name='historicalmovimiento',
            name='tipo_compra',
            field=models.IntegerField(choices=[(1, 'Contado'), (2, 'Crédito')], default=1),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='documento',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Factura'), (2, 'Recibo'), (3, 'Vale')], default=1),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='motivo',
            field=models.TextField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='nombre_cuenta',
            field=models.TextField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Ingreso'), (2, 'Venta'), (3, 'Baja')]),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_baja',
            field=models.IntegerField(choices=[(1, 'Pérdida'), (2, 'Robo'), (3, 'Devolución'), (4, 'Caducidad'), (5, 'Daño')], default=1),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipo_compra',
            field=models.IntegerField(choices=[(1, 'Contado'), (2, 'Crédito')], default=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='area',
            field=models.IntegerField(blank=True, choices=[(1, 'Barra'), (2, 'Mesas'), (3, 'Pista'), (4, 'Servicio'), (5, 'VIP')], null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='clasificacion_empleado',
            field=models.IntegerField(blank=True, choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto')], null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='grupo',
            field=models.IntegerField(blank=True, choices=[(1, 'Bodeguero'), (2, 'Mesero'), (3, 'Cajero'), (4, 'Administrador'), (5, 'Cocina')], null=True),
        ),
    ]
